# Site settings
title: "Izzie Fitzzie"
email: "Izzie.Fitzzie@gmail.com"
description: "Southern Girl's Pursuit of Abs"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: "izzie_fitzzie"
github_username:  "izziez"

# Build settings
markdown: kramdown
